### ISSUE TITLE
Segmentation with DrawEM mandatory to perform surface reconstruction?

### ISSUE THREAD

**Issue by fleurgaudfernau** [DevelopmentalImagingMCRI/MCRIBS#8]
Hello,
I just installed MCRIBS to perform cortical surface extraction on fetal MRIs.

I successfully ran tissue segmentation as follows:
`MCRIBReconAll --tissueseg subjid --subjectage 28`

Unfortunately, when trying the next step (surface reconstruction), I encountered the follow error message:

```
Running command:
	MCRIBSurfReconDeformableMCRIBS 026 --jointhreshold 1
cp: impossible d'évaluer 'TissueSegMCRIBS/026/026_labelfusionimage_dkt_antsinit.nii.gz': Aucun fichier ou dossier de ce type
Using large ventricles: False
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'TissueSegMCRIBS/026/026_drawem_alberts_tissueseg.nii.gz'

```

It seems MCRIBSurfReconDeformableMCRIBS expects tissue segmentation to be performed by DrawEM, and not MCRIBS ( default option).

I tried to re-run segmentation using DrawEM as follows, but DrawEM does not seem to be supported  anymore. After modifying a few lines of code for it to be called properly, I encountered the following error:
```
Running command:
	MCRIBTissueSegDrawEM 026 28
MCRIBS/bin/MCRIBTissueSegDrawEM: ligne 33: MCRIBS/bin/.././MIRTK/MIRTK/Packages/DrawEM/pipelines/neonatal-pipeline-v1.1.sh: Aucun fichier ou dossier de ce type
```

Any help would be very welcome!
Thanks in advance,
Fleur

**Comment by chrisadamsonmcri** [comment]
Hi Fleur,

You are right I don't have the DrawEM method in there anymore.

Try the latest master branch or the Docker/Singularity container and let me know what happens.

**Comment by chrisadamsonmcri** [comment]
Apologies for the long delay.

**Comment by fleurgaudfernau** [comment]
Hello Chris,
Thank you, everything works way better now!
Fleur
